from .deploy_linear import remove_fakequantize_and_collect_params
from .deploy_nnie import remove_fakequantize_and_collect_params_nnie
from .deploy_onnx_qlinear import ONNXQLinearPass
from .deploy_onnx_qnn import ONNXQNNPass
