name: Push Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          ref: ${{ github.event.pull_request.head.sha }}
    - name: Print PR number and title
      run: |
        echo "PR number: ${{ github.event.pull_request.number }}"
        echo "PR title: ${{ github.event.pull_request.title }}"          
    - name: Cache Docker images
      uses: actions/cache@v2
      with:
        path: |
          ~/.docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*') }}

    - name: Run Tests in Docker
      run: |
        pwd
        ls
        docker run -v  "$(pwd):/workspace" sophgo/tpuc_dev:v3.3-cuda bash -c \
        "
        pwd
        ls
        pip show sophgo_mq
        python setup.py install
        cd test
        bash run_test_demo.sh
        "
