name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          days-before-stale: 120
          days-before-close: 7
          stale-issue-message: 'This issue has not received any updates in 120 days. Please reply to this issue if this still unresolved!'
          stale-pr-message: 'This PR has not received any updates in 120 days. Please reply to this issue if this still unresolved!'
          days-before-pr-close: -1
